stages:
  - Build

"yoso-apigen":
  tags:
    - build-vm-shell
  stage: Build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)(-dev)?$/'
  script:
    - cp ./src/shaihulud.jar yoso-apigen.jar
    - echo "$CI_COMMIT_TAG" > "version"
    - jar uf yoso-apigen.jar version
    - jar uf yoso-apigen.jar -C src schema.json
    - jar uf yoso-apigen.jar -C src php7-client-guzzle
    - jar uf yoso-apigen.jar -C src php8-server-symfony
    - rm version
  artifacts:
    name: yoso-apigen-$CI_COMMIT_TAG
    paths:
      - yoso-apigen.jar
    expire_in: 31 day
