stages:
  - Build

"yoso-apigen":
  tags:
    - build-vm-shell
  stage: Build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)(-dev)?$/'
  script:
    - rm -rdf yoso-apigen
    - cp -r src yoso-apigen
  artifacts:
    name: yoso-apigen-$CI_COMMIT_TAG
    paths:
      - ./yoso-apigen/*
    expire_in: 31 day
