stages:
  - Build

"yoso-apigen":
  tags:
    - build-vm-shell
  stage: Build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)(-dev)?$/'
  script:
    - chmod +x build.sh
    - build.sh "$CI_COMMIT_TAG"
  artifacts:
    name: yoso-apigen-$CI_COMMIT_TAG
    paths:
      - ./yoso-apigen.jar
    expire_in: 31 day
